### ISSUE TITLE
Zonein rebranding to "Mapping the Future"

### ISSUE THREAD

**Issue by benlk** [INN/umbrella-citylimits#30]
From [Helpscout 3447](https://secure.helpscout.net/conversation/800410803/3447/)

- [x] Replace the Zonein header image with the image attached to that email
- [x] Remove the heading text above the header image
- [ ] Rename "ZoneIn" to "Mapping the Future" in menus, page titles, and other places in code
- [x] Change order of page to:
    1. News
    2. Videos
    3. Opinions
    4. Map
    5. the bar leading with "What is zoning?"
    6. Documents
    7. the bar of buttons

These changes will need to be made in https://github.com/INN/umbrella-citylimits/blob/master/wp-content/themes/citylimits/page-neighborhoods.php

**Comment by benlk** [comment]
Fix this, too:

> Fatal error: Uncaught Error: Call to undefined function gravity_form() in /Users/blk/sites/citylimits/wp-content/themes/citylimits/page-neighborhoods.php:353 Stack trace: #0 /Users/blk/sites/citylimits/wp-includes/template-loader.php(74): include() #1 /Users/blk/sites/citylimits/wp-blog-header.php(19): require_once('/Users/blk/site...') #2 /Users/blk/sites/citylimits/index.php(17): require('/Users/blk/site...') #3 /Users/blk/.composer/vendor/laravel/valet/server.php(158): require('/Users/blk/site...') #4 {main} thrown in /Users/blk/sites/citylimits/wp-content/themes/citylimits/page-neighborhoods.php on line 353
